"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GN_ROUTER_METHOD_METADATA = 'GN_ROUTER_METHOD_METADATA';
exports.GN_ROUTER_PATH_METADATA = 'GN_ROUTER_PATH_METADATA';
exports.GN_ROUTER_CONTROLLER_PREFIX_METADATA = 'GN_ROUTER_CONTROLLER_PREFIX_METADATA';
exports.GN_ROUTER_MIDDLEWARE_METADATA = 'GN_ROUTER_MIDDLEWARE_METADATA';
var GN_ROUTER_METHOD;
(function (GN_ROUTER_METHOD) {
    GN_ROUTER_METHOD["GET"] = "GET";
    GN_ROUTER_METHOD["POST"] = "POST";
})(GN_ROUTER_METHOD = exports.GN_ROUTER_METHOD || (exports.GN_ROUTER_METHOD = {}));
