"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var AUTHORIZE_ROLE;
(function (AUTHORIZE_ROLE) {
    AUTHORIZE_ROLE[AUTHORIZE_ROLE["ADMIN_USER"] = 1] = "ADMIN_USER";
    AUTHORIZE_ROLE[AUTHORIZE_ROLE["INDIVIDUAL_USER"] = 2] = "INDIVIDUAL_USER";
    AUTHORIZE_ROLE[AUTHORIZE_ROLE["BUSINESS_USER"] = 4] = "BUSINESS_USER";
    AUTHORIZE_ROLE[AUTHORIZE_ROLE["CUSTOMER_SERVICE_USER"] = 8] = "CUSTOMER_SERVICE_USER";
})(AUTHORIZE_ROLE || (AUTHORIZE_ROLE = {}));
exports.default = AUTHORIZE_ROLE;
