"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const gn_enum_1 = require("../gn-enum");
class GN_ERROR_CODE extends gn_enum_1.default {
}
exports.default = GN_ERROR_CODE;
GN_ERROR_CODE.SUCCESS = new GN_ERROR_CODE('00000');
GN_ERROR_CODE.UNKNOWN_ERROR = new GN_ERROR_CODE('00001');
GN_ERROR_CODE.NETWORK_ERROR = new GN_ERROR_CODE('00002');
GN_ERROR_CODE.INTERNAL_SERVER_ERROR = new GN_ERROR_CODE('00003');
GN_ERROR_CODE.CACHE_ERROR = new GN_ERROR_CODE('00004');
GN_ERROR_CODE.DATABASE_ERROR = new GN_ERROR_CODE('00005');
GN_ERROR_CODE.CREATE_TRANSACTION_ERROR = new GN_ERROR_CODE('00006');
GN_ERROR_CODE.HTTP_GET_ERROR = new GN_ERROR_CODE('00007');
GN_ERROR_CODE.HTTP_POST_ERROR = new GN_ERROR_CODE('00008');
GN_ERROR_CODE.JWT_GENERATION_ERROR = new GN_ERROR_CODE('00009');
GN_ERROR_CODE.TOO_MANY_REQUEST = new GN_ERROR_CODE('10001');
GN_ERROR_CODE.UNAUTHORIZED = new GN_ERROR_CODE('10002');
GN_ERROR_CODE.UNPROCESSABLE_ENTITY = new GN_ERROR_CODE('10003');
