"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var GN_HTTP_CODE;
(function (GN_HTTP_CODE) {
    GN_HTTP_CODE[GN_HTTP_CODE["OK"] = 200] = "OK";
    GN_HTTP_CODE[GN_HTTP_CODE["BAD_REQUEST"] = 400] = "BAD_REQUEST";
    GN_HTTP_CODE[GN_HTTP_CODE["UNAUTHORIZED"] = 401] = "UNAUTHORIZED";
    GN_HTTP_CODE[GN_HTTP_CODE["FORBIDDEN"] = 403] = "FORBIDDEN";
    GN_HTTP_CODE[GN_HTTP_CODE["NOT_FOUND"] = 404] = "NOT_FOUND";
    GN_HTTP_CODE[GN_HTTP_CODE["UN_PROCESSABLE_ENTITY"] = 422] = "UN_PROCESSABLE_ENTITY";
    GN_HTTP_CODE[GN_HTTP_CODE["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR";
    GN_HTTP_CODE[GN_HTTP_CODE["NOT_IMPLEMENTED"] = 501] = "NOT_IMPLEMENTED";
    GN_HTTP_CODE[GN_HTTP_CODE["BAD_GATEWAY"] = 502] = "BAD_GATEWAY";
    GN_HTTP_CODE[GN_HTTP_CODE["SERVICE_UNAVAILABLE"] = 503] = "SERVICE_UNAVAILABLE";
})(GN_HTTP_CODE || (GN_HTTP_CODE = {}));
exports.default = GN_HTTP_CODE;
